//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncyclopediaType", Namespace="http://schemas.datacontract.org/2004/07/L1.WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class EncyclopediaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.EncyclopediaPartType[] PartListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderField, value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp1.ServiceReference1.EncyclopediaPartType[] PartList {
            get {
                return this.PartListField;
            }
            set {
                if ((object.ReferenceEquals(this.PartListField, value) != true)) {
                    this.PartListField = value;
                    this.RaisePropertyChanged("PartList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncyclopediaPartType", Namespace="http://schemas.datacontract.org/2004/07/L1.WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class EncyclopediaPartType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.EncyclopediaArticleInfoType[] ArticleInfoListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameEncyclopediaPartTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp1.ServiceReference1.EncyclopediaArticleInfoType[] ArticleInfoList {
            get {
                return this.ArticleInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticleInfoListField, value) != true)) {
                    this.ArticleInfoListField = value;
                    this.RaisePropertyChanged("ArticleInfoList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderField, value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameEncyclopediaPartType {
            get {
                return this.NameEncyclopediaPartTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NameEncyclopediaPartTypeField, value) != true)) {
                    this.NameEncyclopediaPartTypeField = value;
                    this.RaisePropertyChanged("NameEncyclopediaPartType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncyclopediaArticleInfoType", Namespace="http://schemas.datacontract.org/2004/07/L1.WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class EncyclopediaArticleInfoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFileFullArticleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameShortArticleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mark {
            get {
                return this.MarkField;
            }
            set {
                if ((this.MarkField.Equals(value) != true)) {
                    this.MarkField = value;
                    this.RaisePropertyChanged("Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameFileFullArticle {
            get {
                return this.NameFileFullArticleField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFileFullArticleField, value) != true)) {
                    this.NameFileFullArticleField = value;
                    this.RaisePropertyChanged("NameFileFullArticle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameShortArticle {
            get {
                return this.NameShortArticleField;
            }
            set {
                if ((object.ReferenceEquals(this.NameShortArticleField, value) != true)) {
                    this.NameShortArticleField = value;
                    this.RaisePropertyChanged("NameShortArticle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncyclopediaArticleType", Namespace="http://schemas.datacontract.org/2004/07/L1.WcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class EncyclopediaArticleType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainArticleTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameArticleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFileWithArticleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] NameFileWithImgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainArticleText {
            get {
                return this.MainArticleTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MainArticleTextField, value) != true)) {
                    this.MainArticleTextField = value;
                    this.RaisePropertyChanged("MainArticleText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameArticle {
            get {
                return this.NameArticleField;
            }
            set {
                if ((object.ReferenceEquals(this.NameArticleField, value) != true)) {
                    this.NameArticleField = value;
                    this.RaisePropertyChanged("NameArticle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameFileWithArticle {
            get {
                return this.NameFileWithArticleField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFileWithArticleField, value) != true)) {
                    this.NameFileWithArticleField = value;
                    this.RaisePropertyChanged("NameFileWithArticle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] NameFileWithImg {
            get {
                return this.NameFileWithImgField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFileWithImgField, value) != true)) {
                    this.NameFileWithImgField = value;
                    this.RaisePropertyChanged("NameFileWithImg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEncyclopediaService")]
    public interface IEncyclopediaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetInfo", ReplyAction="http://tempuri.org/IEncyclopediaService/GetInfoResponse")]
        WindowsFormsApp1.ServiceReference1.EncyclopediaType GetInfo(string curDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetInfo", ReplyAction="http://tempuri.org/IEncyclopediaService/GetInfoResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EncyclopediaType> GetInfoAsync(string curDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetPart", ReplyAction="http://tempuri.org/IEncyclopediaService/GetPartResponse")]
        WindowsFormsApp1.ServiceReference1.EncyclopediaPartType GetPart(string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetPart", ReplyAction="http://tempuri.org/IEncyclopediaService/GetPartResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EncyclopediaPartType> GetPartAsync(string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetArticle", ReplyAction="http://tempuri.org/IEncyclopediaService/GetArticleResponse")]
        WindowsFormsApp1.ServiceReference1.EncyclopediaArticleType GetArticle(string sPart, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/GetArticle", ReplyAction="http://tempuri.org/IEncyclopediaService/GetArticleResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EncyclopediaArticleType> GetArticleAsync(string sPart, string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/Test", ReplyAction="http://tempuri.org/IEncyclopediaService/TestResponse")]
        void Test(string sDirectory, WindowsFormsApp1.ServiceReference1.EncyclopediaType encyclopediaType, WindowsFormsApp1.ServiceReference1.EncyclopediaPartType encyclopediaPartType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/Test", ReplyAction="http://tempuri.org/IEncyclopediaService/TestResponse")]
        System.Threading.Tasks.Task TestAsync(string sDirectory, WindowsFormsApp1.ServiceReference1.EncyclopediaType encyclopediaType, WindowsFormsApp1.ServiceReference1.EncyclopediaPartType encyclopediaPartType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/Test2", ReplyAction="http://tempuri.org/IEncyclopediaService/Test2Response")]
        void Test2(string sDirectory, WindowsFormsApp1.ServiceReference1.EncyclopediaArticleType articleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncyclopediaService/Test2", ReplyAction="http://tempuri.org/IEncyclopediaService/Test2Response")]
        System.Threading.Tasks.Task Test2Async(string sDirectory, WindowsFormsApp1.ServiceReference1.EncyclopediaArticleType articleType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEncyclopediaServiceChannel : WindowsFormsApp1.ServiceReference1.IEncyclopediaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EncyclopediaServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IEncyclopediaService>, WindowsFormsApp1.ServiceReference1.IEncyclopediaService {
        
        public EncyclopediaServiceClient() {
        }
        
        public EncyclopediaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EncyclopediaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncyclopediaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncyclopediaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.ServiceReference1.EncyclopediaType GetInfo(string curDir) {
            return base.Channel.GetInfo(curDir);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EncyclopediaType> GetInfoAsync(string curDir) {
            return base.Channel.GetInfoAsync(curDir);
        }
        
        public WindowsFormsApp1.ServiceReference1.EncyclopediaPartType GetPart(string sCode) {
            return base.Channel.GetPart(sCode);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EncyclopediaPartType> GetPartAsync(string sCode) {
            return base.Channel.GetPartAsync(sCode);
        }
        
        public WindowsFormsApp1.ServiceReference1.EncyclopediaArticleType GetArticle(string sPart, string sCode) {
            return base.Channel.GetArticle(sPart, sCode);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EncyclopediaArticleType> GetArticleAsync(string sPart, string sCode) {
            return base.Channel.GetArticleAsync(sPart, sCode);
        }
        
        public void Test(string sDirectory, WindowsFormsApp1.ServiceReference1.EncyclopediaType encyclopediaType, WindowsFormsApp1.ServiceReference1.EncyclopediaPartType encyclopediaPartType) {
            base.Channel.Test(sDirectory, encyclopediaType, encyclopediaPartType);
        }
        
        public System.Threading.Tasks.Task TestAsync(string sDirectory, WindowsFormsApp1.ServiceReference1.EncyclopediaType encyclopediaType, WindowsFormsApp1.ServiceReference1.EncyclopediaPartType encyclopediaPartType) {
            return base.Channel.TestAsync(sDirectory, encyclopediaType, encyclopediaPartType);
        }
        
        public void Test2(string sDirectory, WindowsFormsApp1.ServiceReference1.EncyclopediaArticleType articleType) {
            base.Channel.Test2(sDirectory, articleType);
        }
        
        public System.Threading.Tasks.Task Test2Async(string sDirectory, WindowsFormsApp1.ServiceReference1.EncyclopediaArticleType articleType) {
            return base.Channel.Test2Async(sDirectory, articleType);
        }
    }
}
